### ISSUE TITLE
Hash for uninterned symbols?

### ISSUE THREAD

**Issue by joinr** [ruricolist/cl-murmurhash#7]
Dependence on `package-symbol` for computing hashes throws an error for symbols with no package, e.g. '#:x .  May not matter in practice.  Clojure's jvm implementation in [Util.java](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Util.java#L164) treats (hash nil) as 0.

Possible naive solution is to detect lack of package and return empty string or similar constant:
```
(defmethod murmurhash ((s symbol) &key (seed *default-seed*) mix-only)
  (let ((hash seed)
        (pkg (let ((p (symbol-package s)))
               (if p  (package-name p) "")))
        (sym (symbol-name s)))
    (mixf hash pkg)
    (mixf hash sym)
    (if mix-only
        hash
        (finalize hash (+ (length pkg) (length sym))))))
```
Unsure if this has broader implications (e.g. toward distribution of hashes), but it seems plausible to this layman.

Proposed diff attached (github doesn't support diff format...):
[patch.diff.txt](https://github.com/ruricolist/cl-murmurhash/files/3950073/patch.diff.txt)

With this implemented, we get:
```
MURMURHASH> (murmurhash '#:x)
4207307701
MURMURHASH> (murmurhash 'x)
1349100184
```

Thanks for providing this library.

**Comment by ruricolist** [comment]
Not being able to hash gensyms is definitely a bug, thanks. I've merged your fix.
