### ISSUE TITLE
"Uniqueness" fades at 1 mil

### ISSUE THREAD

**Issue by Harag** [ruricolist/cl-murmurhash#9]
```
(let ((hashes))
    (dotimes (x 1000000)
      (push (cl-murmurhash:murmurhash (list :emp-no x)) hashes))
    
    (format t "Hashes created ~A~%" (length hashes))
    (setf hashes (remove-duplicates hashes))
    (format t "Hash duplicates removed ~A~%" (length hashes)))
```
> Hashes created 1000000
> Hash duplicates removed 999998

Is this to be expected or is it a bug?

**Comment by ruricolist** [comment]
Murmurhash is not a cryptographic hash algorithm, so yes, collisions are to be expected.

**Comment by Harag** [comment]
Just out of curiosity would a 128 bit version have a bigger "range" before it experiences collisions?

**Comment by ruricolist** [comment]
That seems likely.

**Comment by Harag** [comment]
Thanx

**Comment by priyadarshan** [comment]
Collisions can be tricky, 128 bit is good. Git uses sha1 at 160 bit . You may find this page, [Hash function quality and speed tests ](https://github.com/rurban/smhasher) useful too.
